apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-upload-download-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-upload-download-app
  template:
    metadata:
      labels:
        app: py-upload-download-app
    spec:
      containers:
      - name: py-upload-download-app
        image: quay.io/rh_ee_swongpai/py-upload-download:b7ac2366c4964a611f02aee37afe1b1c19417192
        ports:
        - containerPort: 5123
        env:
        - name: UPLOAD_FOLDER
          value: "/out"
        - name: SAVEPASS
          value: "YOURPASSWORD"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - mountPath: /out/compliance/ocp
          name: data-volume
        - mountPath: /out/compliance/worker
          name: worker-volume
        - mountPath: /out/compliance/master
          name: master-volume
        # add more for who have MCP for infra and another.
        # - mountPath: /out/compliance/infra        
        #   name: infra-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ocp4-cis
      - name: worker-volume
        persistentVolumeClaim:
          claimName: ocp4-cis-node-worker
      - name: master-volume
        persistentVolumeClaim:
          claimName: ocp4-cis-node-master
      # add more for who have MCP for infra and another.
