apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-upload-download-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-upload-download-app
  template:
    metadata:
      labels:
        app: py-upload-download-app
    spec:
      containers:
      - name: py-upload-download-app
        image: quay.io/rh_ee_swongpai/py-upload-download:3970f3b5d9f5032468e2fabdb86d5cebdec48f8f
        ports:
        - containerPort: 5123
        env:
        - name: UPLOAD_FOLDER
          value: "/app/demo-data"
        - name: SAVEPASS
          value: "YOURPASSWORD"
        volumeMounts:
        - name: data-volume
          mountPath: /app/demo-data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      imagePullSecrets:
      - name: quay-sec
